### PR TITLE
OV-181: Add new migrations to update email field max length to 320

### LINKED ISSUE #181: BUG: Email field in Sign up and Sign in forms can't contain more than 255 characters
### Describe your issue

In the requirements it is stated, that Email field "should have minlength 6 characters and maxlength 320". Actually, when the length is > 255 or <= 320 characters, it results in error.

### Steps to reproduce

**In Postman:**
1. Create a POST request to http://bsa-2024-outreachvids-dev.eu-north-1.elasticbeanstalk.com/sign-up.
2. Enter the body where email contains from 256 to 320 characters:
```
{
  "email": "olenaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa@gmail.com",
  "fullName": "Olena Test",
  "password": "123456",
   "confirmPassword": "123456"
}
```
3. Send the request.

**In the browser:**
1. Open the page http://bsa-2024-outreachvids-dev.eu-north-1.elasticbeanstalk.com/sign-up.
2. In the Full Name field enter the valid full name, for example Olena Test.
3. In the Email field enter the email, which is > 255 ot <= 320 characters long, for example olenaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa@gmail.com.
4. In the Password field enter the valid password, for example 123456.
5. In the Repeat Password field repeat the password, for example 123456.
6. Press the Sign Up button.

### What was the actual result?
**In Postman:**
```
500 Internal Server Error
{
    "errorType": "COMMON",
    "message": "insert into \"users\" (\"created_at\", \"email\", \"full_name\", \"password_hash\", \"password_salt\", \"updated_at\") values ($1, $2, $3, $4, $5, $6) returning * - значение не умещается в тип character varying(255)"
}
```
**In the browser:**
User gets an error message "An error occured. [database info] * - значение не умещается в тип character varying(255)". Please check the screenshot below.

### What was the expected result?
**In Postman:**
`200 OK`

In the browser:
User can register an account with the email, which is > 255 ot <= 320 characters long.

### Put here any screenshots or videos (optional)

Image

Image

Image

### What OS are you seeing the problem on?

Windows 11

### What browsers are you seeing the problem on?

Firefox 129.0.2 (64x)
Chrome 128.0.6613.113 (x64)

### Severity

Minor (S4)

### LINKED ISSUE #184: BUG: Error messages from backend are unclear, contain unnecessary tech details and non-English text
### Describe your issue

Some error messages from backend are unclear, contain unnecessary tech details and non-English text

### Steps to reproduce

**In the browser:**

**Option 1: Email length issue**
1. Open the page http://localhost:3000/sign-up.
2. In the Full Name field enter the valid full name, for example Olena Test.
3. In the Email field enter the email, which is > 255 ot <= 320 characters long, for example [olenaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa@gmail.com](mailto:olenaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa@gmail.com).
4. In the Password field enter the valid password, for example 123456.
5. In the Repeat Password field repeat the password, for example 123456.
6. Press the Sign Up button.

**Option 2: Duplicate user issue**
1. Open the page http://localhost:3000/sign-up.
2. In the Full Name field enter the valid full name, for example Olena Test.
3. In the Email field enter the valid email, for example: olena@gmail.com.
4. In the Password field enter the valid password, for example 123456.
5. In the Repeat Password field repeat the password, for example 123456.
6. Press the Sign Up button.
7. Click Log Out.
8. Open the page http://localhost:3000/sign-up.
9. In the Full Name field enter the valid full name, for example Olena Test.
10. In the Email field enter the valid email, for example: olena@gmail.com.
11. In the Password field enter the valid password, for example 123456.
12. In the Repeat Password field repeat the password, for example 123456.
13. Press the Sign Up button.

### What was the actual result?

Both options: The user gets an error message which is not clear and contains unnecessary technical details, please check the screenshots.

### What was the expected result?

Option 1: The user gets a standard user-friendly error message, e. g. "Please  enter a valid email."
Option 2: The user gets a standard user-friendly error message, e. g. "This user already exists."

### Put here any screenshots or videos (optional)

Option 1:

Image

Option 2 (created by Wilson Bravo):

Image

### What OS are you seeing the problem on?

Windows 11

### What browsers are you seeing the problem on?

Firefox 129.0.2 (64x)
Chrome 128.0.6613.113 (x64)

### Severity

Minor (S4)

### PR DESCRIPTION
**Pull request by stefano-lacorazza**
Summary
This PR creates a new migration file to update the maximum length of the email field in the USERS table. This change addresses the error that occurs when a new user registers with an email length between 255 and 320 characters.

Details

- Migration: Adds a new migration to alter the email column length to 320 characters.
- Issue: Fixes the error encountered during user registration with long email addresses.

Changes

- Created a new migration file 20240815120000_update_email_length.ts.
- Updated the email column in the USERS table to have a maximum length of 320 characters.

Please remember to reapply migrations when testing and after merge

https://github.com/user-attachments/assets/294a0eea-c985-41bb-bead-531ae8bbb525

Used email with 315 chars: yourname_unique_id_1234_abcdefghij_klmnop111qrstuvwxyz_001234567890_thelonganddetailednameforyourservicea123aazccasdsasdaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa@example.com

### CODE REVIEW

File: backend/src/migrations/20240815120000_update_email_length.ts [hunk 1]
```diff
@@ -0,0 +1,18 @@
+import { type Knex } from 'knex';
+
+const TABLE_NAME = 'users';
+const COLUMN_NAME = 'email';
+
+async function up(knex: Knex): Promise<void> {
+    await knex.schema.alterTable(TABLE_NAME, (table) => {
+        table.string(COLUMN_NAME, 320).alter();
```
Comment (JKaypa) [inline backend/src/migrations/20240815120000_update_email_length.ts]: is not better to make another const for length? also, the table and column name shouldn't have the actual name ?

Comment (stefano-lacorazza) [reply backend/src/migrations/20240815120000_update_email_length.ts]: Great suggestion about the 320 as a constant. The column name is defined as a const at the beginning of the file

**Review by sofiia-trokhymchuk — APPROVED** [review]

**Review by nikita-remeslov — APPROVED** [review]
