### PR TITLE
OV-424: Error when selecting background before avatar

### LINKED ISSUE #424: BUG: Error when selecting template before avatar in /studio page
### Describe your issue

When using the /studio page, selecting an avatar followed by a template works correctly. However, if the user selects a template first (even if it is the same one), followed by an avatar, an error occurs. This sequence causes the system to fail to render the avatar properly.

### Steps to reproduce

1. Go to the /studio page.
2. Click on the scenes tab and click on templates option
3. Select a template from the available options.
4. Then select an avatar.
5. Observe the error in the video preview

### What was the actual result?

https://github.com/user-attachments/assets/8ae5e3f6-0501-477e-9336-a136c09f8bb7

### What was the expected result?

The avatar should be rendered properly regardless of whether the template or avatar is selected first. There should be no error when selecting a template followed by an avatar.

### Put here any screenshots or videos (optional)

_No response_

### What OS are you seeing the problem on?

Windows

### What browsers are you seeing the problem on?

Chrome, Safari, Edge, Firefox, Opera

### Severity

Critical (S2)

### PR DESCRIPTION
**Pull request by Sanchousina**
The bug is fixed. User can add background before the avatar to the scene and vice versa

### CODE REVIEW

File: frontend/src/bundles/studio/components/video/video.tsx [hunk 1]
```diff
@@ -38,19 +37,28 @@ const VideoComponent: React.FC<Properties> = ({ scenes, scripts }) => {
...
-                                    />
-                                </Flex>
+                            {scene?.avatar?.url ? (
+                                <RemotionImg
+                                    className={styles['avatar']}
+                                    src={scene?.avatar?.url ?? ''}
+                                />
                             ) : (
                                 <></>
                             )}
```
Comment (anton-otroshchenko) [inline frontend/src/bundles/studio/components/video/video.tsx:47]: can we just use && instead without returning the <></>

Comment (Sanchousina) [reply frontend/src/bundles/studio/components/video/video.tsx:47]: no, the video player breaks, I tried it

**Review by sofiia-trokhymchuk — APPROVED** [review]
